<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".heatmap">
    <ImageView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:src="@drawable/heatmap"
        android:layout_gravity="center_horizontal"
        android:layout_marginTop="50px"
        />
    <ImageView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:src="@drawable/legends"
        android:layout_gravity="center_horizontal"
        android:layout_marginTop="200px"
        />
    <LinearLayout

        android:layout_width="400dp"
        android:layout_centerHorizontal="true"
        android:layout_marginTop="150dp"
        android:orientation="vertical"
        android:background="@drawable/border"
        android:layout_height="400dp">
        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="200dp"
            android:orientation="horizontal"
            >
            <TextView
                android:layout_width="200dp"
                android:layout_height="200dp"
                android:background="#4CAF50"
                android:text="90"
                android:textAlignment="center"
                android:textSize="30dp"
                android:id="@+id/loadcell11"
                ></TextView>
            <TextView
                android:layout_width="200dp"
                android:layout_height="200dp"
                android:background="#E91E63"
                android:text="90"
                android:textAlignment="center"
                android:textSize="30dp"
                android:id="@+id/loadcell21"
                ></TextView>
        </LinearLayout>
        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="200dp"
            android:orientation="horizontal"
            >
            <TextView
                android:layout_width="200dp"
                android:layout_height="200dp"
                android:background="#FF5722"
                android:text="90"
                android:textAlignment="center"
                android:textSize="30dp"
                android:id="@+id/loadcell31"
                ></TextView>
            <TextView
                android:layout_width="200dp"
                android:layout_height="200dp"
                android:background="#FFEB3B"
                android:text="90"
                android:textAlignment="center"
                android:textSize="30dp"
                android:id="@+id/loadcell41"
                ></TextView>
        </LinearLayout>

    </LinearLayout>

</RelativeLayout>